/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package diegoChicaza;

/**
 *
 * @author Viny
 */
public class Potencia extends javax.swing.JFrame {

    /**
     * Creates new form Potencia
     */
    public Potencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnIgual = new javax.swing.JButton();
        jtxtBase = new javax.swing.JTextField();
        jtxtExpo = new javax.swing.JTextField();
        jtxtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("potencia");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(158, 21, 41, 14);

        jbtnIgual.setText("=");
        jbtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIgual);
        jbtnIgual.setBounds(140, 120, 41, 23);
        getContentPane().add(jtxtBase);
        jtxtBase.setBounds(23, 118, 50, 40);
        getContentPane().add(jtxtExpo);
        jtxtExpo.setBounds(76, 91, 43, 30);
        getContentPane().add(jtxtResultado);
        jtxtResultado.setBounds(190, 120, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
int a, b, res;
a=Integer.valueOf(jtxtBase.getText());
b=Integer.valueOf(jtxtExpo.getText());
//res=a+b;
res=(int)Math.pow(a, b);
jtxtResultado.setText(String.valueOf(res));


//res=Integer.valueOf(jtxtResultado.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Potencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JTextField jtxtBase;
    private javax.swing.JTextField jtxtExpo;
    private javax.swing.JTextField jtxtResultado;
    // End of variables declaration//GEN-END:variables
}
